# Generated by Django 5.1.2 on 2024-10-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0002_remove_cours_illustration_alter_cours_date_debut'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='llustration',
            field=models.ImageField(blank=True, null=True, upload_to='cours_illustrations/'),
        ),
    ]
