# Generated by Django 5.1.2 on 2024-10-12 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('departement', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='professeurs_photos/')),
                ('biographie', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('specialite', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='cours_illustrations/')),
                ('nombre_heures', models.PositiveIntegerField(blank=True, null=True)),
                ('niveau', models.CharField(blank=True, choices=[('débutant', 'Débutant'), ('intermédiaire', 'Intermédiaire'), ('avancé', 'Avancé')], max_length=50, null=True)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='Cours.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='ressources/')),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('note', 'Note'), ('td', 'TD')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='ressources_illustrations/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='Cours.cours')),
            ],
        ),
    ]
