# Generated by Django 5.1.2 on 2024-10-12 20:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='illustration',
        ),
        migrations.AlterField(
            model_name='cours',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
