# Generated by Django 5.1.2 on 2024-10-12 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0003_cours_llustration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='llustration',
            new_name='illustration',
        ),
    ]
