# Generated by Django 5.1.2 on 2024-10-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0004_rename_llustration_cours_illustration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('word', 'WORD'), ('excel', 'EXCEL'), ('python', 'PYTHON'), ('power', 'POWER')], max_length=100),
        ),
    ]
